import { essentialIconSearchData } from "./essentialIconSearchData.ts";

export const essentialIcons = [
  ["message-text", "Chat"],
  ["bot", "Bot"],
  ["star", "Star"],
  ["spark-solid", "Spark"],
  ["bright-star", "Bright Star"],
  ["page", "Document"],
  ["folder", "Folder"],
  ["clock", "Clock"],
  ["bell", "Bell"],
  ["search", "Search"],
  ["computer", "Computer"],
  ["smartphone-device", "Phone"],
  ["key", "Key"],
  ["capabilities", "Capabilities"],
  ["edit-pencil", "Pencil"],
  ["check", "Check"],
  ["play", "Play"],
  ["send", "Send"],
  ["heart", "Heart"],
  ["home", "Home"],
  ["bookmark", "Bookmark"],
  ["book", "Book"],
  ["brain", "Brain"],
  ["light-bulb", "Light Bulb"],
  ["leaf", "Leaf"],
  ["flower", "Flower"],
  ["tree", "Tree"],
  ["cloud", "Cloud"],
  ["sun-light", "Sun"],
  ["moon-sat", "Moon"],
  ["rain", "Rain"],
  ["wind", "Wind"],
  ["snow-flake", "Snowflake"],
  ["music-note", "Music Note"],
  ["camera", "Camera"],
  ["palette", "Palette"],
  ["asterisk", "Asterisk"],
  ["flare", "Flare"],
  ["infinite", "Infinity"],
  ["code", "Code"],
  ["code-brackets", "Code Brackets"],
  ["terminal", "Terminal"],
  ["database", "Database"],
  ["dashboard", "Dashboard"],
  ["dashboard-dots", "Dashboard Dots"],
  ["dashboard-speed", "Speedometer"],
  ["control-slider", "Control Slider"],
  ["barcode", "Barcode"],
  ["server", "Server"],
  ["globe", "Globe"],
  ["rocket", "Rocket"],
  ["planet", "Planet"],
  ["language", "Language"],
  ["translate", "Translate"],
  ["graduation-cap", "Graduation Cap"],
  ["flask", "Flask"],
  ["dna", "Dna"],
  ["atom", "Atom"],
  ["radiation-solid", "Radiation"],
  ["magnet-solid", "Magnet"],
  ["sine-wave", "Sine Wave"],
  ["square-wave", "Square Wave"],
  ["sigma-function", "Sigma Function"],
  ["arc-3d", "3D Arc"],
  ["cube", "Cube"],
  ["cube-scan", "Cube Scan"],
  ["cylinder", "Cylinder"],
  ["fillet-3d", "3D Fillet"],
  ["sphere", "Sphere"],
  ["hexagon", "Hexagon"],
  ["depth", "Depth"],
  ["microscope", "Microscope"],
  ["math-book", "Math Book"],
  ["calculator", "Calculator"],
  ["wallet", "Wallet"],
  ["coins", "Coins"],
  ["cash", "Cash"],
  ["credit-card", "Credit Card"],
  ["cart", "Cart"],
  ["bag", "Bag"],
  ["suitcase", "Suitcase"],
  ["airplane", "Airplane"],
  ["car", "Car"],
  ["truck", "Truck"],
  ["motorcycle", "Motorcycle"],
  ["bicycle", "Bicycle"],
  ["train", "Train"],
  ["map", "Map"],
  ["map-pin", "Map Pin"],
  ["compass", "Compass"],
  ["sea-waves", "Sea Waves"],
  ["fish", "Fish"],
  ["running", "Running"],
  ["arrow-archery", "Archery"],
  ["basketball", "Basketball"],
  ["football", "Football"],
  ["gym", "Gym"],
  ["trophy", "Trophy"],
  ["medal", "Medal"],
  ["gamepad", "Gamepad"],
  ["puzzle", "Puzzle"],
  ["wrench", "Wrench"],
  ["hammer", "Hammer"],
  ["tools", "Tools"],
  ["ruler", "Ruler"],
  ["design-pencil", "Design Pencil"],
  ["color-picker", "Color Picker"],
  ["pen-tablet", "Pen Tablet"],
  ["emoji", "Emoji"],
  ["laptop", "Laptop"],
  ["linux", "Linux"],
  ["apple", "Apple"],
  ["github", "Github"],
  ["git-branch", "Git Branch"],
  ["calendar", "Calendar"],
  ["journal", "Journal"],
  ["lock", "Lock"],
  ["shield-check", "Shield Check"],
  ["fingerprint", "Fingerprint"],
  ["iris-scan", "Iris Scan"],
  ["eye", "Eye"],
  ["light-bulb-on", "Light Bulb On"],
  ["sound-high", "Sound High"],
  ["microphone", "Microphone"],
  ["headset", "Headset"],
  ["network", "Network"],
  ["wifi", "Wifi"],
  ["internet", "Internet"],
  ["link", "Link"],
  ["attachment", "Attachment"],
  ["book-stack", "Book Stack"],
  ["open-book", "Open Book"],
  ["coffee-cup", "Coffee"],
  ["mail", "Email"],
  ["gift", "Gift"],
  ["bed", "Sleep"],
  ["umbrella", "Umbrella"],
  ["building", "Building"],
  ["industry", "Industry"],
  ["church", "Faith"],
  ["piggy-bank", "Savings"],
  ["battery-indicator", "Battery"],
  ["cooling-square-solid", "Cooling"],
  ["bonfire", "Campfire"],
  ["dice-six", "Dice"],
  ["wolf", "Wolf"],
  ["package", "Package"],
  ["director-chair", "Movies"],
  ["lamp", "Lamp"],
  ["fridge", "Kitchen"],
  ["user", "Person"],
] as const;

const reservedIcons = new Set([
  // Icons used by Arura controls and navigation must keep one meaning.
  "attachment",
  "bot",
  "brain",
  "capabilities",
  "message-text",
  "network",
  "check",
  "clock",
  "cloud",
  "computer",
  "edit-pencil",
  "eye",
  "folder",
  "key",
  "page",
  "rocket",
  "search",
  "send",
  "settings",
  "smartphone-device",
  "star",
  "terminal",
  "light-bulb-on",
  "code-brackets",
  "book-stack",
  "open-book",
  "tools",
  "bag",
  "medal",
  "internet",
  "calendar",
  "puzzle",
]);

export const essentialIconChoices = essentialIcons.filter(
  ([icon]) => !reservedIcons.has(icon),
);

const searchAliases: Record<string, string> = {
  "arc-3d": "arc3d arch curve shape",
  bed: "rest bedroom",
  "bright-star": "night sky celestial astronomy",
  cash: "banknotes dollars currency",
  "coffee-cup": "beverage",
  coins: "currency savings wealth",
  "cooling-square-solid": "temperature air conditioning cold",
  "cube-scan": "object physical shape volume",
  "director-chair": "cinema movie film",
  "fillet-3d": "fillet3d rounded edge modeling",
  flare: "burst radiance",
  fridge: "kitchen appliance",
  gift: "present birthday celebration",
  industry: "factory manufacturing production",
  "iris-scan": "eye biometric identity security",
  journal: "writing",
  leaf: "sustainability environment",
  "magnet-solid": "magnetism physics attraction",
  "moon-sat": "lunar night sky space",
  "radiation-solid": "radioactive nuclear hazard",
  "sine-wave": "waveform signal frequency audio math",
  "spark-solid": "sparkle glitter magic ai",
  "square-wave": "waveform signal digital frequency",
  "sun-light": "sunshine sunny sky daylight",
  truck: "freight lorry vehicle delivery",
  wolf: "pet wildlife",
};

function normalizeSearch(value: string): string {
  return value
    .normalize("NFKD")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function searchEssentialIcons(query: string) {
  const terms = normalizeSearch(query).split(/\s+/).filter(Boolean);
  if (!terms.length) return essentialIconChoices;

  return essentialIconChoices
    .map((choice, index) => {
      const [icon, label] = choice;
      const name = normalizeSearch(`${icon} ${label}`);
      const related = normalizeSearch(
        `${essentialIconSearchData[icon] ?? ""} ${searchAliases[icon] ?? ""}`,
      );
      if (
        !terms.every((term) => name.includes(term) || related.includes(term))
      ) {
        return undefined;
      }
      const score = terms.reduce(
        (total, term) => total + (name.includes(term) ? 2 : 1),
        0,
      );
      return { choice, index, score };
    })
    .filter((result) => result !== undefined)
    .sort((a, b) => b.score - a.score || a.index - b.index)
    .map((result) => result.choice);
}
