export const essentialIcons = [
  ["chat-bubble", "Chat"],
  ["bot", "Bot"],
  ["star", "Star"],
  ["page", "Document"],
  ["folder", "Folder"],
  ["clock", "Clock"],
  ["bell", "Bell"],
  ["search", "Search"],
  ["computer", "Computer"],
  ["smartphone-device", "Phone"],
  ["key", "Key"],
  ["capabilities", "Capabilities"],
  ["edit-pencil", "Pencil"],
  ["check", "Check"],
  ["play", "Play"],
  ["send", "Send"],
  ["heart", "Heart"],
  ["home", "Home"],
  ["bookmark", "Bookmark"],
  ["book", "Book"],
  ["brain", "Brain"],
  ["light-bulb", "Light Bulb"],
  ["leaf", "Leaf"],
  ["flower", "Flower"],
  ["tree", "Tree"],
  ["cloud", "Cloud"],
  ["music-note", "Music Note"],
  ["camera", "Camera"],
  ["palette", "Palette"],
  ["code", "Code"],
  ["code-brackets", "Code Brackets"],
  ["terminal", "Terminal"],
  ["database", "Database"],
  ["server", "Server"],
  ["globe", "Globe"],
  ["rocket", "Rocket"],
  ["planet", "Planet"],
  ["language", "Language"],
  ["translate", "Translate"],
  ["graduation-cap", "Graduation Cap"],
  ["flask", "Flask"],
  ["dna", "Dna"],
  ["atom", "Atom"],
  ["microscope", "Microscope"],
  ["math-book", "Math Book"],
  ["calculator", "Calculator"],
  ["wallet", "Wallet"],
  ["credit-card", "Credit Card"],
  ["cart", "Cart"],
  ["bag", "Bag"],
  ["suitcase", "Suitcase"],
  ["airplane", "Airplane"],
  ["car", "Car"],
  ["bicycle", "Bicycle"],
  ["train", "Train"],
  ["map", "Map"],
  ["map-pin", "Map Pin"],
  ["compass", "Compass"],
  ["sea-waves", "Sea Waves"],
  ["fish", "Fish"],
  ["running", "Running"],
  ["basketball", "Basketball"],
  ["football", "Football"],
  ["gym", "Gym"],
  ["trophy", "Trophy"],
  ["medal", "Medal"],
  ["gamepad", "Gamepad"],
  ["puzzle", "Puzzle"],
  ["wrench", "Wrench"],
  ["hammer", "Hammer"],
  ["tools", "Tools"],
  ["ruler", "Ruler"],
  ["design-pencil", "Design Pencil"],
  ["color-picker", "Color Picker"],
  ["pen-tablet", "Pen Tablet"],
  ["emoji", "Emoji"],
  ["laptop", "Laptop"],
  ["windows", "Windows"],
  ["linux", "Linux"],
  ["apple", "Apple"],
  ["github", "Github"],
  ["git-branch", "Git Branch"],
  ["calendar", "Calendar"],
  ["journal", "Journal"],
  ["lock", "Lock"],
  ["shield-check", "Shield Check"],
  ["fingerprint", "Fingerprint"],
  ["eye", "Eye"],
  ["light-bulb-on", "Light Bulb On"],
  ["sound-high", "Sound High"],
  ["microphone", "Microphone"],
  ["headset", "Headset"],
  ["network", "Network"],
  ["wifi", "Wifi"],
  ["internet", "Internet"],
  ["link", "Link"],
  ["attachment", "Attachment"],
  ["book-stack", "Book Stack"],
  ["open-book", "Open Book"],
] as const;

const reservedIcons = new Set([
  "attachment",
  "bot",
  "capabilities",
  "chat-bubble",
  "check",
  "clock",
  "cloud",
  "computer",
  "edit-pencil",
  "folder",
  "key",
  "page",
  "rocket",
  "search",
  "send",
  "smartphone-device",
  "star",
  "terminal",
]);

export const essentialIconChoices = essentialIcons.filter(
  ([icon]) => !reservedIcons.has(icon),
);
