// Categories and tags from Iconoir's iconoir.com/icons.csv at d7dfa4d0341df0670bfed9fc24221c9d7ef2112e.
// This index contains only the curated Essentials icons.
export const essentialIconSearchData: Record<string, string> = {
  "spark-solid": "Other ai artificial intelligence magic new highlight",
  "bright-star": "Gaming favorite rating review bookmark",
  "bell": "Communication notification alert ring sound reminder",
  "play": "Music start run media video",
  "heart": "Health love favorite like health",
  "home": "Home house main start residence",
  "bookmark": "Organization save favorite marker tab",
  "book": "Activities read education library learn",
  "light-bulb": "Home idea brightness lamp insight bulb",
  "leaf": "Nature eco nature plant green",
  "flower": "Activities plant bloom garden nature",
  "tree": "Nature nature plant forest green",
  "sun-light": "Weather day brightness weather light lamp bulb idea",
  "moon-sat": "Science night dark mode sleep",
  "rain": "Weather weather storm water wet",
  "wind": "Weather weather air fresh breeze forecast",
  "snow-flake": "Weather weather storm ac air conditioner freeze freezer winter cold flake",
  "music-note": "Music audio song note sound",
  "camera": "Photos and Videos photo picture lens shoot selfie",
  "palette": "Activities colors swatch theme design",
  "asterisk": "Typography star wildcard required footnote",
  "flare": "Shapes geometry figure vector draw",
  "infinite": "Science limitless endless boundless unbounded unlimited loop forever repeat",
  "code": "Development develop programming source script",
  "database": "Database db storage repo sql server data",
  "dashboard": "System accelerate acceleration panel speed metrics analytics home",
  "dashboard-dots": "System accelerate acceleration panel speed metrics analytics home",
  "dashboard-speed": "System accelerate acceleration panel metrics analytics home",
  "control-slider": "System controller ui element dashboard panel setting computer os settings desktop slider handle adjust parameter",
  "barcode": "Shopping scan sku product inventory",
  "server": "Connectivity connection computer network hosting backend cloud database",
  "globe": "Communication world earth international map",
  "planet": "Science space orbit astro science",
  "language": "Other misc general utility ui",
  "translate": "Other language i18n locale global",
  "graduation-cap": "Science school education diploma student",
  "flask": "Science science lab chemistry experiment",
  "dna": "Science genetics biology science helix",
  "atom": "Science science chemistry physics nuclear",
  "radiation-solid": "Science lab research experiment study",
  "magnet-solid": "Science attract science polarity lab research experiment study",
  "sine-wave": "Science lab research experiment study",
  "square-wave": "Science shape box checkbox region",
  "sigma-function": "3D Editor greek math symbol 3d modeling mesh render",
  "arc-3d": "3D Editor modeling blender 4d 3d mesh render",
  "cube": "3D Editor modeling blender 4d solid model object 3d box volume",
  "cube-scan": "3D Editor 3d measure ar lidar box volume solid qr barcode camera detect",
  "cylinder": "3D Editor shape geometry 3d modeling mesh render",
  "fillet-3d": "3D Editor 3d modeling mesh render",
  "sphere": "3D Editor modeling blender 4d geometry ball 3d globe shape",
  "hexagon": "Shapes shape polygon six sides",
  "depth": "Science lab research experiment study",
  "microscope": "Science lab research experiment study",
  "math-book": "Activities read education library learn",
  "calculator": "System math operation computer os settings desktop",
  "wallet": "Finance money cards purse finance",
  "coins": "Finance money payment banking budget",
  "cash": "Finance money bills currency payment",
  "credit-card": "Finance payment visa checkout billing",
  "cart": "Shopping shopping basket ecommerce checkout",
  "suitcase": "Clothing luggage travel bag rollaboard",
  "airplane": "Transport fly jet plane flight travel airline",
  "car": "Transport vehicle auto drive driving transport",
  "truck": "Transport ship semitruck shipment amazon delivery shipping vehicle cargo",
  "motorcycle": "Transport travel vehicle commute trip",
  "bicycle": "Transport cycle bike transport sport life activity cycling pedal",
  "train": "Transport transport train station track public rail metro locomotive",
  "map": "Maps location gps travel directions",
  "map-pin": "Maps location marker place gps travel directions map attach",
  "compass": "Navigation navigation direction map orient",
  "sea-waves": "Activities sport hobby leisure outdoor",
  "fish": "Animals seafood animal ocean swim",
  "running": "Activities run jog sport fitness",
  "arrow-archery": "Activities sport activity arrows direction navigate pointer chevron move bow arrow target",
  "basketball": "Activities sport hobby leisure outdoor",
  "football": "Activities soccer sport ball game",
  "gym": "Activities fitness workout dumbbell weights",
  "trophy": "Activities winner award achievement prize",
  "gamepad": "Gaming game play controller fun",
  "wrench": "Tools tool settings repair fix",
  "hammer": "Tools utility build repair wrench",
  "ruler": "Design Tools measure size distance design",
  "design-pencil": "Design Tools draw sketch prototype ui",
  "color-picker": "Design Tools palette paint tint hue",
  "pen-tablet": "Devices write draw edit signature",
  "emoji": "Emojis emotion face reaction sticker",
  "laptop": "Devices notebook computer macbook work",
  "linux": "System os operative system ubuntu terminal open source tux",
  "apple": "Food fruit food ios mac",
  "github": "Git git github",
  "git-branch": "Git git github version branch commit merge",
  "journal": "Docs diary notes book log",
  "lock": "Security secure password private encrypt",
  "shield-check": "Security security protection firewall safe trust done success tick approve ok complete",
  "fingerprint": "Identity biometric identity touchid auth",
  "iris-scan": "Identity qr barcode camera detect",
  "sound-high": "Audio audio volume speaker listen",
  "microphone": "Audio sound music speaker listen",
  "headset": "Music earphones earbuds listenings audio headphones support call",
  "wifi": "Connectivity signal connection network wireless internet",
  "link": "Other url hyperlink chain attach",
  "coffee-cup": "Food cafe drink morning caffeine",
  "mail": "Communication email message inbox letter",
  "gift": "Other misc general utility ui",
  "bed": "Home sleep home sleeping house domestic appliance interior",
  "umbrella": "Clothing rain parasol weather cover sunshade",
  "building": "Buildings city office architecture place",
  "industry": "Buildings architecture city place urban",
  "church": "Buildings religion wedding building faith",
  "piggy-bank": "Finance money finance building cash",
  "battery-indicator": "Other energy source charge power level electric",
  "cooling-square-solid": "Science shape box checkbox region",
  "bonfire": "Activities sport hobby leisure outdoor",
  "dice-six": "Gaming random game chance roll",
  "wolf": "Animals animal dog wild nature",
  "package": "Transport ship shipment amazon box travel vehicle commute trip",
  "director-chair": "Home movie cinema hollywood film filming house domestic appliance interior",
  "lamp": "Home light home house desk brightness fixture",
  "fridge": "Home kitchen appliance cold food",
  "user": "Users person people ux account profile avatar",
};
